import React, { useMemo } from "react";
import { View, StyleSheet, Pressable, Share, Platform } from "react-native";
import Animated, { FadeInDown } from "react-native-reanimated";
import { Feather } from "@expo/vector-icons";
import * as Haptics from "expo-haptics";

import { ScreenScrollView } from "@/components/ScreenScrollView";
import { ThemedText } from "@/components/ThemedText";
import { Button } from "@/components/Button";
import { useTheme } from "@/hooks/useTheme";
import { useAuth } from "@/context/AuthContext";
import { useLanguage } from "@/context/LanguageContext";
import { useData } from "@/context/DataContext";
import { Spacing, BorderRadius, AttendanceColors } from "@/constants/theme";

export default function EarningsScreen() {
  const { theme } = useTheme();
  const { user } = useAuth();
  const { t } = useLanguage();
  const { payments, segments, sessions } = useData();

  const totalEarnings = useMemo(() => {
    return payments.reduce((sum, p) => sum + p.amount, 0);
  }, [payments]);

  const monthlyEarnings = useMemo(() => {
    const now = new Date();
    const startOfMonth = new Date(now.getFullYear(), now.getMonth(), 1);
    return payments
      .filter((p) => new Date(p.paidAt) >= startOfMonth)
      .reduce((sum, p) => sum + p.amount, 0);
  }, [payments]);

  const totalClasses = useMemo(() => {
    return sessions.reduce((sum, s) => sum + s.classesTaken, 0);
  }, [sessions]);

  const totalStudents = useMemo(() => {
    return segments.length;
  }, [segments]);

  const subjects = useMemo(() => {
    return [...new Set(segments.map((s) => s.subject))];
  }, [segments]);

  const handleDownloadPortfolio = async () => {
    if (Platform.OS !== "web") {
      Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium);
    }

    const portfolioText = `
${user?.name}'s Tutoring Portfolio
Generated by ShikkhaJar

Total Classes: ${totalClasses}
Total Students: ${totalStudents}
Subjects: ${subjects.join(", ") || "None"}
Total Earnings: ৳${totalEarnings}

Monthly Breakdown:
${sessions
  .slice(0, 10)
  .map(
    (s) =>
      `- ${s.month} ${s.year}: ${s.classesTaken} classes, ৳${s.amountPaid}`
  )
  .join("\n")}
    `.trim();

    try {
      await Share.share({
        message: portfolioText,
        title: `${user?.name}'s Teaching Portfolio`,
      });
    } catch (error) {
      console.error("Error sharing portfolio:", error);
    }
  };

  const handleSendReminder = async (segmentId: string) => {
    if (Platform.OS !== "web") {
      Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
    }
  };

  const pendingPayments = useMemo(() => {
    return segments.filter((s) => {
      const lastPayment = payments
        .filter((p) => p.segmentId === s.id)
        .sort((a, b) => new Date(b.paidAt).getTime() - new Date(a.paidAt).getTime())[0];

      if (!lastPayment) return true;

      const cycleStart = new Date(lastPayment.cycleEnd);
      const now = new Date();
      const daysDiff = Math.floor(
        (now.getTime() - cycleStart.getTime()) / (1000 * 60 * 60 * 24)
      );
      return daysDiff >= s.targetDays;
    });
  }, [segments, payments]);

  return (
    <ScreenScrollView>
      <Animated.View entering={FadeInDown.delay(100).duration(400)}>
        <ThemedText type="h2" style={styles.title}>
          {t("earnings")}
        </ThemedText>
      </Animated.View>

      <Animated.View entering={FadeInDown.delay(200).duration(400)} style={styles.earningsCard}>
        <View style={[styles.totalCard, { backgroundColor: theme.primary + "15" }]}>
          <ThemedText type="small" style={[styles.cardLabel, { color: theme.primary }]}>
            {t("totalEarnings")}
          </ThemedText>
          <ThemedText type="h1" style={{ color: theme.primary }}>
            ৳{totalEarnings.toLocaleString()}
          </ThemedText>
        </View>

        <View style={styles.statsRow}>
          <View style={[styles.statCard, { backgroundColor: theme.secondary + "15" }]}>
            <ThemedText type="h3" style={{ color: theme.secondary }}>
              ৳{monthlyEarnings.toLocaleString()}
            </ThemedText>
            <ThemedText type="small" style={{ color: theme.secondary }}>
              {t("thisMonth")}
            </ThemedText>
          </View>
          <View style={[styles.statCard, { backgroundColor: AttendanceColors.present + "15" }]}>
            <ThemedText type="h3" style={{ color: AttendanceColors.present }}>
              {totalClasses}
            </ThemedText>
            <ThemedText type="small" style={{ color: AttendanceColors.present }}>
              {t("classesTaken")}
            </ThemedText>
          </View>
        </View>
      </Animated.View>

      {pendingPayments.length > 0 ? (
        <Animated.View entering={FadeInDown.delay(300).duration(400)}>
          <ThemedText type="h4" style={styles.sectionTitle}>
            {t("paymentPending")}
          </ThemedText>
          {pendingPayments.map((segment) => (
            <View
              key={segment.id}
              style={[styles.pendingCard, { backgroundColor: theme.warning + "15" }]}
            >
              <View style={styles.pendingInfo}>
                <ThemedText type="body" style={{ fontWeight: "600" }}>
                  {segment.partnerName}
                </ThemedText>
                <ThemedText type="small" style={{ color: theme.textSecondary }}>
                  {segment.subject} - ৳{segment.monthlyFee}
                </ThemedText>
              </View>
              <Pressable
                onPress={() => handleSendReminder(segment.id)}
                style={[styles.reminderButton, { backgroundColor: theme.warning }]}
              >
                <Feather name="bell" size={16} color="#FFFFFF" />
                <ThemedText type="small" style={{ color: "#FFFFFF", fontWeight: "600" }}>
                  {t("sendReminder")}
                </ThemedText>
              </Pressable>
            </View>
          ))}
        </Animated.View>
      ) : null}

      <Animated.View entering={FadeInDown.delay(400).duration(400)} style={styles.portfolioSection}>
        <ThemedText type="h4" style={styles.sectionTitle}>
          Portfolio
        </ThemedText>
        <View style={[styles.portfolioCard, { backgroundColor: theme.backgroundDefault }]}>
          <View style={styles.portfolioStats}>
            <View style={styles.portfolioStat}>
              <Feather name="users" size={20} color={theme.primary} />
              <ThemedText type="body">{totalStudents} Students</ThemedText>
            </View>
            <View style={styles.portfolioStat}>
              <Feather name="book" size={20} color={theme.primary} />
              <ThemedText type="body">{subjects.length} Subjects</ThemedText>
            </View>
            <View style={styles.portfolioStat}>
              <Feather name="calendar" size={20} color={theme.primary} />
              <ThemedText type="body">{totalClasses} Classes</ThemedText>
            </View>
          </View>
          <Button onPress={handleDownloadPortfolio}>
            {t("downloadPortfolio")}
          </Button>
        </View>
      </Animated.View>
    </ScreenScrollView>
  );
}

const styles = StyleSheet.create({
  title: {
    marginBottom: Spacing.xl,
  },
  earningsCard: {
    marginBottom: Spacing.xl,
  },
  totalCard: {
    padding: Spacing.xl,
    borderRadius: BorderRadius.lg,
    alignItems: "center",
    marginBottom: Spacing.md,
  },
  cardLabel: {
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: Spacing.xs,
  },
  statsRow: {
    flexDirection: "row",
    gap: Spacing.md,
  },
  statCard: {
    flex: 1,
    padding: Spacing.lg,
    borderRadius: BorderRadius.md,
    alignItems: "center",
  },
  sectionTitle: {
    marginBottom: Spacing.md,
  },
  pendingCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: Spacing.lg,
    borderRadius: BorderRadius.md,
    marginBottom: Spacing.sm,
  },
  pendingInfo: {
    flex: 1,
  },
  reminderButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.xs,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    borderRadius: BorderRadius.sm,
  },
  portfolioSection: {
    marginTop: Spacing.xl,
  },
  portfolioCard: {
    padding: Spacing.xl,
    borderRadius: BorderRadius.lg,
  },
  portfolioStats: {
    gap: Spacing.md,
    marginBottom: Spacing.xl,
  },
  portfolioStat: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.md,
  },
});
